const GET_HITS_REQUEST = "GET_HITS_REQUEST";
const GET_HITS_FAILURE = "GET_HITS_FAILUR";
const GET_HITS_SUCCESS = "GET_HITS_SUCCESS";

const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILUR";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

const GET_CATALOG_REQUEST = "GET_CATALOG_REQUEST";
const GET_CATALOG_FAILURE = "GET_CATALOG_FAILUR";
const GET_CATALOG_SUCCESS = "GET_CATALOG_SUCCESS";

const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
const CHANGE_SEARCH_SUCCESS = " CHANGE_SEARCH_SUCCESS";

const CHANGE_SEARCHICON_VALUE = "CHANGE_SEARCHICON_VALUE";

const GET_GOOD_REQUEST = "GET_GOOD_REQUEST";
const GET_GOOD_FAILURE = "GET_GOOD_FAILUR";
const GET_GOOD_SUCCESS = "GET_GOOD_SUCCESS";

const CHANGE_CART_STATE = "CHANGE_CART_STATE";
const CHANGE_CART_SUCCESS = "CHANGE_CART_SUCCESS";

const CHANGE_CATEGORY_ID = "CHANGE_CATEGORY_ID";
const CHANGE_CATEGORY_SUCCESS = "CHANGE_CATEGORY_SUCCESS";

const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";
const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";

export {
  GET_HITS_REQUEST,
  GET_HITS_FAILURE,
  GET_HITS_SUCCESS,
  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_FAILURE,
  GET_CATEGORIES_SUCCESS,
  GET_CATALOG_REQUEST,
  GET_CATALOG_FAILURE,
  GET_CATALOG_SUCCESS,
  CHANGE_SEARCH_FIELD,
  CHANGE_SEARCH_SUCCESS,
  GET_GOOD_REQUEST,
  GET_GOOD_FAILURE,
  GET_GOOD_SUCCESS,
  CHANGE_CART_STATE,
  CHANGE_CART_SUCCESS,
  CHANGE_CATEGORY_ID,
  CHANGE_CATEGORY_SUCCESS,
  POST_ORDER_REQUEST,
  POST_ORDER_FAILURE,
  POST_ORDER_SUCCESS,
  CHANGE_SEARCHICON_VALUE,
};
